Implement all
Resci/jv-spring-intro pull request #3
Opened 2021-02-10 02:41 UTC by Resci

2021-02-10 09:25 UTC, Max-Pochepets approved these changes

2021-02-10 21:54 UTC, AndriiBardin approved these changes

2021-02-11 08:44 UTC, Sofasmile requested changes

2021-02-11 08:44 UTC, Sofasmile commented on src/main/java/com/mate/controller/UserController.java
> +        return UserMapper.toDto(userService.get(userId));
let's make UserMapper a component and remove static from the method

2021-02-11 08:44 UTC, Sofasmile commented on src/main/java/com/mate/dao/UserDao.java
> +    User get(Long id);
```suggestion
    Optional<User> get(Long id);
```

2021-02-11 08:44 UTC, Sofasmile commented on src/main/java/com/mate/dao/UserDaoImpl.java
> +            return session.createQuery("FROM User where id = :id", User.class)
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_03.html

> Don’t complicate get by id methods in your DAO, use session.get().

2021-02-11 08:44 UTC, Sofasmile commented on src/main/java/com/mate/service/UserMapper.java
> +    public static UserResponseDto toDto(User user) {
```suggestion
    public static UserResponseDto mapToDto(User user) {
```

2021-02-11 08:44 UTC, Sofasmile commented on src/main/java/com/mate/service/UserMapper.java
> +    public static User toObj(UserResponseDto dto) {
where do we use this method? Let's remove it)

2021-02-11 09:08 UTC, Sofasmile approved these changes

2021-02-11 09:14 UTC, merged